services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: han
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    restart: always
    command: >
      bash -c "
      apt-get update && apt-get install -y wget &&
      wget -q -O /docker-entrypoint-initdb.d/northwind.sql https://raw.githubusercontent.com/pthom/northwind_psql/master/northwind.sql &&
      docker-entrypoint.sh postgres
      "
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    restart: always

  grafana:
    image: grafana/grafana:9.1.7
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - /Users/hanseul/Desktop/dev/repository/Grafana
    restart: always